### ISSUE TITLE
How to disable dynatrace-oneagent-webhook from helm chat values in dynatrace-oneagent-operator chart

### ISSUE THREAD

**Issue by lcnsir** [Dynatrace/helm-charts#100]
Hi guys:
If I do not need the dynatrace-oneagent-webhook deployment in dynatrace-oneagent-operator chart , how could I disable it fairily , without delete it directly ?  since from the chart templates,  it's has the same template condition as the operator yaml spec.

maybe  we could make a new args in values.yaml to disable it ? if some use cases does not required the feature.

Thanks

**Comment by benj5656** [comment]
Could you use something like this?

Add a section to values file:
webhook
  enabled: false

Edit helm-charts/dynatrace-operator/templates/Common/webhook/deployment-webhook.yaml:
{{- $platformIsSet := printf "%s" (required "Platform needs to be set to kubernetes or openshift" (include "dynatrace-operator.platformSet" .))}}
{{- if Values.webhook.enabled }}
apiVersion: apps/v1

You would need to delete the webhook from any existing deployments, but this _should_ allow you to control whether to deploy it or not next time?

(note - I haven't tested this myself!)

**Comment by luhi-DT** [comment]
Hi. I will close that issue since the OneAgentOperator will be deprecated in the near future, therefore we are not going to implement new features at that point. Please have a look at the DynatraceOperator instead. Thanks!
