### ISSUE TITLE
Proxy setting is not passed to dynakube-classic ds

### ISSUE THREAD

**Issue by benj5656** [Dynatrace/helm-charts#101]
When setting the proxy in helm override file, the value seems to be passed as container args.

However, the pods fail to connect to the tenant. You can see below that the container does not get https_proxy value set:

  Containers:
   dynatrace-oneagent:
    Image:      REMOVED/oneagent:1.52.1000
    Port:       <none>
    Host Port:  <none>
    Args:
      **--set-proxy=$(https_proxy)**
      --set-host-property=OperatorVersion=v0.2.1
      --set-deployment-metadata=orchestration_tech=Operator
      --set-deployment-metadata=script_version=v0.2.1
      --set-deployment-metadata=orchestrator_id=REMOVED
    Requests:
      cpu:      100m
    Readiness:  exec [/bin/sh -c grep -q oneagentwatchdo /proc/[0-9]*/stat] delay=30s timeout=1s period=30s #success=1 #failure=3
    Environment:
      DT_K8S_NODE_NAME:                     (v1:spec.nodeName)
      DT_K8S_CLUSTER_ID:                   REMOVED
      ONEAGENT_INSTALLER_TOKEN:            <set to the key 'paasToken' in secret 'dynakube'>  Optional: false
      ONEAGENT_INSTALLER_SCRIPT_URL:       https://REMOVED.live.dynatrace.com/api/v1/deployment/installer/agent/unix/default/latest?Api-Token=$(ONEAGENT_INSTALLER_TOKEN)&arch=x86&flavor=default
      ONEAGENT_INSTALLER_SKIP_CERT_CHECK:  false
      https_proxy:                         
      ONEAGENT_ENABLE_VOLUME_STORAGE:      true

...

    Environment:
      DT_K8S_NODE_NAME:                     (v1:spec.nodeName)
      DT_K8S_CLUSTER_ID:                   REMOVED
      ONEAGENT_INSTALLER_TOKEN:            <set to the key 'paasToken' in secret 'dynakube'>  Optional: false
      ONEAGENT_INSTALLER_SCRIPT_URL:       https://REMOVED.live.dynatrace.com/api/v1/deployment/installer/agent/unix/default/latest?Api-Token=$(ONEAGENT_INSTALLER_TOKEN)&arch=x86&flavor=default
      ONEAGENT_INSTALLER_SKIP_CERT_CHECK:  false
      https_proxy:                         
      ONEAGENT_ENABLE_VOLUME_STORAGE:      true

When I manually set the container env https_proxy to my proxy server, connections can be made.

**Comment by chrismuellner** [comment]
Thanks for letting us know.
Could you please create a proper support ticket so we can investigate and try to reproduce the issue?

Thanks
