### ISSUE TITLE
[Dynatrace Operator] secret/dynatrace-helm looks for ProxyKey 

### ISSUE THREAD

**Issue by JKrehling** [Dynatrace/helm-charts#102]
27m         Warning   Failed              pod/dynakube-helm-kubemon-0                              Error: couldn't find key ProxyKey in Secret dynatrace/dynakube-helm

The kubemon and routing pods are looking for a key in the secret called ProxyKey but you only have 

kubectl edit secret dynakube-helm -n dynatrace

apiVersion: v1
data:
  apiToken: 
  paasToken: 
  proxy: 

data fields in the secret so if you configure a proxy in the base configs it will fail

**Comment by JKrehling** [comment]
![image](https://user-images.githubusercontent.com/25485833/128919114-681efefc-b957-4dc1-b3d4-c444b799567c.png)
Use 
kubectl edit secret dynakube-helm -n dynatrace

And copy the key value for proxy into a new one called ProxyKey and then save

**Comment by DTMad** [comment]
Hey @JKrehling,

with the latest release 
https://github.com/Dynatrace/helm-charts/releases/tag/dynatrace-operator-v0.2.2
we changed the logic so we look for the data.proxy filed for the ActiveGate pods.
