### ISSUE TITLE
Helm install dynatrace-operator, the secret "dynakube-pull-secret" for pulling activegate image is missing 

### ISSUE THREAD

**Issue by cathyzhang05** [Dynatrace/helm-charts#127]
After the installation, the pod "dynakube-routing-0" and "dynakube-kubemon-0" are failed to start due to fail to pull the image "activegate:latest" from dynatrace server. 
I looked into the manifest of StatefulSet "dynakube-routing"  and "dynakube-kubemon", the "imagePullSecrets" is "dynakube-pull-secret". But no secret named "dynakube-pull-secret" generated after installation. 
Would you please help take a look? Thank you.

**Comment by cathyzhang05** [comment]
Hi @DTMad ,
Thanks for your kindly response, we use the HEAD version.

**Comment by DTMad** [comment]
Please don't use the master branch since this is used as your development branch.
Try to stick to a released version.

If you experience troubles feel free to open a support ticket so we can have a proper look:
https://www.dynatrace.com/support/contact-support/

**Comment by cathyzhang05** [comment]
Hi @DTMad ,
Due to the master branch included the changes fixed our problem: https://github.com/Dynatrace/helm-charts/pull/126, https://github.com/Dynatrace/helm-charts/pull/124.

**Comment by DTMad** [comment]
I see.
Could you please double check the image you're using for the operator?
Referring there to 0.2.2 should be fine and they the fix for the PullSecret should be in place.

**Comment by cathyzhang05** [comment]
Thanks @DTMad ,  we have set the customPullSecret to other values, so the secret "dynakube-pull-secret" is not generated. Right now it's working now.
