### ISSUE TITLE
Allow creating the dynakubes CRD as part of the helm chart

### ISSUE THREAD

**Issue by abh1kg** [Dynatrace/helm-charts#131]
I would like to see the dynakubes CRD being installed as part of the helm chart instead of having to install it before running `helm install`. This is already supported by [helm](https://helm.sh/docs/chart_best_practices/custom_resource_definitions/) and reduces the extra operational effort for users.

**Comment by gkrenn** [comment]
Hi, thanks for the info.

We have already discussed this internally and decided against it as helm currently [does not support](https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#:~:text=There%20is%20no%20support%20at%20this%20time%20for%20upgrading%20or%20deleting%20CRDs%20using%20Helm) upgrading of CRDs.

**Comment by abh1kg** [comment]
@gkrenn : That's unfortunately true but I believe it's still worthwhile to put the CRDs in the helm chart instead of having the CRDs in a different location. It's still fine to expect the operators to install the CRDs during an upgrade of the operator release - this is how Nginx [recommends upgrading their helm release](https://docs.nginx.com/nginx-ingress-controller/installation/installation-with-helm/#upgrading-the-chart).

**Comment by DTMad** [comment]
@abh1kg we decided on doing so since the original repository where the operator lives in is https://github.com/Dynatrace/dynatrace-operator
We create and maintain the CRD there and since we here also release helm charts for the "old" operator:
https://github.com/Dynatrace/dynatrace-oneagent-operator
it would be cumbersome to link to the latest release of the CRD from within the Helm chart releases.

**Comment by abh1kg** [comment]
@DTMad : I understood the rationale now. Thanks 👍

**Comment by KittyKatt** [comment]
Sorry to necro this, but is there any thoughts on creating a dedicated Helm chart around the CRDs themselves? We use Terraform to deploy this chart and deploying the CRD manifest manually is really cumbersome and requires our API to accessible at plan time (which is impossible as the cluster is created as part of the apply).
