### ISSUE TITLE
Dynatrace Operator - CustomProperties are not formatted properly

### ISSUE THREAD

**Issue by evanderbent** [Dynatrace/helm-charts#133]
Hi, If I want to define custom properties, they don't get rendered properly. If I define the following in my values.yaml:

    kubernetesMonitoring:
      enabled: true
      customProperties:
        value: |-
          [connectivity]
          ignoreClusterRuntimeInfo = true
          [collector]
          seedServerUrl = https://customer_url/communication
I get the following error message in helm (using helm template):

    kubernetesMonitoring:
        enabled: true
        replicas: 1
        customProperties:
          value: [connectivity]
    ignoreClusterRuntimeInfo = true
    [collector]
    seedServerUrl = https://customer_url/communication
      routing:
        enabled: true
        replicas: 1
    Error: YAML parse error on dynatrace/templates/Common/customresource-dynakube.yaml: error converting YAML to JSON: yaml: line 49: could not find expected ':'
    helm.go:88: [debug] error converting YAML to JSON: yaml: line 49: could not find expected ':'
    YAML parse error on dynatrace/templates/Common/customresource-dynakube.yaml
    helm.sh/helm/v3/pkg/releaseutil.(*manifestFile).sort
	helm.sh/helm/v3/pkg/releaseutil/manifest_sorter.go:146

I fixed it by changing the helm template rendering to:

    customProperties:
      value: {{  toYaml .Values.kubernetesMonitoring.customProperties.value | indent 6 | trim }}`

That results in a good result:

      kubernetesMonitoring:
        enabled: true
        replicas: 1
        customProperties:
          value: |-
            [connectivity]
            ignoreClusterRuntimeInfo = true
            [collector]
            seedServerUrl = https://customer_url/communication

Please let me know if this solution is good enough for a PR.

**Comment by chrismuellner** [comment]
Fixed in Dynatrace/dynatrace-operator/pull/691
