### ISSUE TITLE
Helm 3 requirement for operator deployment

### ISSUE THREAD

**Issue by gmichels** [Dynatrace/helm-charts#16]
Hello,

The dynatrace-oneagent-operator is set to use `apiVersion` as `v2`, which means the chart requires Helm 3 (see https://github.com/helm/helm-www/blob/master/content/en/docs/topics/charts.md).

https://github.com/Dynatrace/helm-charts/blob/fa4baebbf8912930eadcb6d09bcde3f79ea0ca1a/dynatrace-oneagent-operator/Chart.yaml#L15

Is this by design? If so, can you please update the documentation to state the Helm version 3 requirement?

Thanks

**Comment by lrgar** [comment]
Hello again. Yes, that is correct, it requires Helm 3, and indeed, we should have it documented.

**Comment by gmichels** [comment]
Well that's pity, we are still on Helm 2...

Thanks for the clarification.

**Comment by DTMad** [comment]
Helm 3 charts should be backwards compatible.
Did you try to install it?

**Comment by gmichels** [comment]
@DTMad it doesn't work due to the apiVersion being v2, the Helm client halts the execution.

Any particular reason for this chart to require Helm 3?

**Comment by DTMad** [comment]
Helm 3 is the new standard and should be backwards compatible.

Could you try to just set the apiVersion to v1 instead and see if it works?

**Comment by gmichels** [comment]
Works just fine when manually setting apiVersion to v1. I just had to manually add the CRDs since they are only applied automatically when using Helm 3.

**Comment by DTMad** [comment]
Glad to hear that! 👍

**Comment by gmichels** [comment]
Do you guys plan on changing the chart to have the api version set to v1? Having to manually download and mangle the version isn’t very good for production systems and future upgrades.
