### ISSUE TITLE
helm repo gives 404 error 

### ISSUE THREAD

**Issue by amisca-fss** [Dynatrace/helm-charts#169]
the helm repo for dynatrace operator is giving off an 404 error 

https://raw.githubusercontent.com/Dynatrace/helm-charts/master/repos/stable

**Comment by chrismuellner** [comment]
what's not working for you?

When you add this URL as a repo to helm and then install the operator using this repo, there's no need to directly access that folder:
```
helm repo add dynatrace https://raw.githubusercontent.com/Dynatrace/helm-charts/master/repos/stable
...
helm install dynatrace-operator dynatrace/dynatrace-operator
```

**Comment by amisca-fss** [comment]
this is the result I'm getting both in the terraform module and my local
```

 helm repo add dynatrace https://raw.githubusercontent.com/Dynatrace/helm-charts/master/repos/stable
Error: looks like "https://raw.githubusercontent.com/Dynatrace/helm-charts/master/repos/stable" is not a valid chart repository or cannot be reached: Get "https://raw.githubusercontent.com/Dynatrace/helm-charts/master/repos/stable/index.yaml": EOF
```

**Comment by amisca-fss** [comment]
today it seems that the error is solved
