### ISSUE TITLE
Link https://raw.githubusercontent.com/Dynatrace/helm-charts/master/repos/stable return 404

### ISSUE THREAD

**Issue by rkaeffer** [Dynatrace/helm-charts#171]
# 404 Error on https://raw.githubusercontent.com/Dynatrace/helm-charts/master/repos/stable

The link https://raw.githubusercontent.com/Dynatrace/helm-charts/master/repos/stable, which is indicate in README file at first step : Adding Dynatrace OneAgent Helm repository is not available anymore.

Maybe to replace with https://github.com/Dynatrace/helm-charts/blob/master/repos/stable/index.yaml ?

Regards,

**Comment by chrismuellner** [comment]
This is expected behavior. The `index.yaml` file is expected in this folder, the folder does not need to actually point to anything. If you check `https://raw.githubusercontent.com/Dynatrace/helm-charts/master/repos/stable/index.yaml` you see that it resolves correctly.
