### ISSUE TITLE
Optional secret creation

### ISSUE THREAD

**Issue by Fabian-K** [Dynatrace/helm-charts#18]
Hi,

we are using https://github.com/bitnami-labs/sealed-secrets to provision secrets in our cluster. Is it possible that the creation of the Secret that is used by the agent is made optional when using the helm chart? With that, we could continue provisioning all secrets using sealed-secrets (which then creates the actual secret in the cluster).

Thanks,
Fabian

**Comment by DTMad** [comment]
Hey!

Thanks for your feedback! We will schedule this and let you know once it's done.

Thanks,
Marco

**Comment by DTMad** [comment]
Created an internal ticket for this feature.

**Comment by kav** [comment]
Worth noting: the current implementation doesn't match the docs. It currently says the secret name is the parameter but in actuality it's using the value not the content of a secret with that name

secret.apiToken | name of the secret that holds the API token from above |  
-- | -- | --
secret.paasToken | name of the secret that holds the PaaS token from above |  

https://www.dynatrace.com/support/help/technology-support/cloud-platforms/kubernetes/oneagent-with-helm/

**Comment by jkleinlercher** [comment]
I also use bitnami sealed secrets. And now I am totally confused. I see the oneagent secret is created by bitnami sealed secrets controller. However, during startup of the oneagent pod and downloading the oneagent it uses the sealed-secret value in the URL, not the real secret value. Of course I then get a HTTP 401 from the dynatrace server ... why is the oneagent using the sealed-secret value, not the unsealed value?

```
17:09:41 Started agent deployment as a container, PID 16919.
17:09:41 Downloading agent to /tmp/Dynatrace-OneAgent-Linux.sh via ....

**Comment by DTMad** [comment]
Thanks for the hint!
We already noticed and this will be changed in the documentation soon.

**Comment by DTMad** [comment]
https://github.com/Dynatrace/helm-charts/pull/25
Once the PR is merged and we create the new version this will be in

**Comment by toma2711** [comment]
Hey @DTMad is there plan to release a new Helm Chart release with this in? Latest is still 0.7.0 without this. This will really help me!

**Comment by DTMad** [comment]
Hey!
The new version of the helm chart with this feature got released today.
Hope this helps ;)
