### ISSUE TITLE
Outdated charts repo - last version was 0.4.1

### ISSUE THREAD

**Issue by benj5656** [Dynatrace/helm-charts#189]
https://github.com/Dynatrace/helm-charts/tree/master/repos/stable
Can the latest versions be published here? We use chart repo's to ingest helm charts into our platforms.

The dynatrace-operator repo doesn't contain a chart repository.

**Comment by luhi-DT** [comment]
Hi, if I understood that correctly then the dynatrace-operator repository does container a chart repository here: https://github.com/Dynatrace/dynatrace-operator/tree/master/config/helm/repos/stable
