### ISSUE TITLE
automatic-kubernetes-api-monitoring flag

### ISSUE THREAD

**Issue by dannemca-kyndryl** [Dynatrace/helm-charts#192]
Hi team, good day.

Can we have this flag included on the helm-charts by default, so our clusters get connected automatically to our tenants when deployed?

`feature.dynatrace.com/automatic-kubernetes-api-monitoring: "true"`

Thanks.

**Comment by chrismuellner** [comment]
WIth `v0.7.0` you have to define the CR separately and apply it after the helm chart is installed, so you can customize the whole CR to you needs, see [official migration guide](https://www.dynatrace.com/support/help/shortlink/k8s-dto-helm#migrate).
