### ISSUE TITLE
Token for dynatrace Operator

### ISSUE THREAD

**Issue by pahofmann** [Dynatrace/helm-charts#195]
The values.yaml for the dynatrace operator still lists an `apiToken` and `paasToken`.
From the operator documentation it should be `apiToken` and `dataIngestToken` now, how can I set the proper tokens so the API Integration via the deployed AG works as well?

**Comment by chrismuellner** [comment]
The up to date `values.yaml` can be found in the dynatrace-operator repository: [values.yaml](https://github.com/Dynatrace/dynatrace-operator/blob/master/config/helm/chart/default/values.yaml)

Please follow the [helm instructions in the official documentation](https://www.dynatrace.com/support/help/shortlink/k8s-dto-helm#installation) on how to configure these tokens for your operator installation.

**Comment by pahofmann** [comment]
@chrismuellner I can't reopen the issue. If the discussion would be better suited in a support ticket that would be fine aswell.

**Comment by chrismuellner** [comment]
Sorry, the shortlink points to the outdated version. The updated instructions for `v0.7.0` can be found here: https://www.dynatrace.com/support/help/setup-and-configuration/setup-on-container-platforms/kubernetes/get-started-with-kubernetes-monitoring/set-up-k8s-monitoring-with-helm

Those should include all the instructions required to get a working installation with the latest helm chart version.

**Comment by pahofmann** [comment]
That also only shows version 0.6.0 for me, the new version isn't published yet?
![image](https://user-images.githubusercontent.com/5699104/176895410-b11b0532-e9ce-400d-9747-07c47b600557.png)

**Comment by chrismuellner** [comment]
Thanks, links seem to all be pointing to the deprecated instructions.

You can navigate to Container Platforms > Kubernetes/Openshift > Get Started > Set up monitoring with Helm
That should have the latest version. The links will be updated shortly.
