### ISSUE TITLE
[FR] Add the ability to define the securityContext of all software packages

### ISSUE THREAD

**Issue by pierluigilenoci** [Dynatrace/helm-charts#199]
We want to have the ability to define a [securityContext](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/) for all the software deployed with the [Dynatrace Operator Helm Chart](https://github.com/Dynatrace/helm-charts/tree/master/dynatrace-operator/chart/default).

**Comment by meik99** [comment]
This Dynatrace/helm-charts repository has been deprecated. If you have the same issues with the latest charts, please open this issue in the [Dynatrace/dynatrace-operator](https://github.com/Dynatrace/dynatrace-operator) repository
