### ISSUE TITLE
[FR] Add the ability to define the podDisruptionBudget of all software packages

### ISSUE THREAD

**Issue by pierluigilenoci** [Dynatrace/helm-charts#200]
We want to have the ability to define a [podDisruptionBudget](https://kubernetes.io/docs/tasks/run-application/configure-pdb/) for all the software deployed with the [Dynatrace Operator Helm Chart](https://github.com/Dynatrace/helm-charts/tree/master/dynatrace-operator/chart/default).

**Comment by meik99** [comment]
This Dynatrace/helm-charts repository has been deprecated. If you have the same issues with the latest charts, please open this issue in the [Dynatrace/dynatrace-operator](https://github.com/Dynatrace/dynatrace-operator) repository
