### ISSUE TITLE
CSI driver requests.cpu too high?

### ISSUE THREAD

**Issue by rwunderer** [Dynatrace/helm-charts#207]
## Background
We run multiple Kubernetes clusters in AWS. Some of them utilize relatively small instances (t3a.large) with 2 CPU cores.

## Problem
After switching to Dynatrace Operator (installed with this helm chart) we noticed that already *half of your available cpu per node* (`900m`) is reserved for administrative daemonsets leaving us with only half of our computing power for the actual application.

Not all daemons are Dynatrace related, but the biggest reservation is done by `dynatrace-oneagent-csi-driver` with the csi-driver container reserving [`300m` of CPU](https://github.com/Dynatrace/helm-charts/blob/d08456eaba817a41631aa8fda8a85df3ab967a89/dynatrace-operator/chart/default/templates/Common/csi/daemonset.yaml#L77)

Is that value accurate? Or is this meant to be `30m` instead, with maybe a limit of `300m`?

**Comment by luhi-DT** [comment]
Hi, no this is done on purpose, as the CSIDriver is doing some CPU intensive tasks, such as downloading a bigger zip archive and unzipping that. Additionally we try to keep up best practices from kubernetes. Therefore as the CSI Driver is a critical component, we want to get QOS Class `Guaranteed`, which has the prerequisite of setting requests and limits to the exact same value. More here: https://kubernetes.io/docs/tasks/configure-pod-container/quality-service-pod/

Thanks!
Lukas
