### ISSUE TITLE
create dynatrace-monitoring serviceaccount

### ISSUE THREAD

**Issue by jkleinlercher** [Dynatrace/helm-charts#23]
in https://www.dynatrace.com/support/help/technology-support/cloud-platforms/kubernetes/monitoring/connect-kubernetes-clusters-to-dynatrace/ is documented how to create a service account for monitoring k8s in dynatrace.
why not creating this service account in the helm chart?

**Comment by DTMad** [comment]
Hey @jkleinlercher !

We have some plans to change this and make it easier for customers to get their whole K8s cluster into Dynatrace even easier.
This needs good planning and some more time but I hope it fulfils all the needs of our K8s customers ;)

So please stay tuned until we have a first version of the new approach to make your lives easier.

Regards,
Marco

**Comment by DTMad** [comment]
The repository already exists:
https://github.com/Dynatrace/dynatrace-operator
Release is planned for this year

Furthermore there will be a dedicated helm chart for this new operator then.
