### ISSUE TITLE
use chart release name in psp reference

### ISSUE THREAD

**Issue by jkleinlercher** [Dynatrace/helm-charts#24]
In https://github.com/Dynatrace/helm-charts/blob/d5e07b3a9ce4f06deacf87643a63d4f26f86e538/dynatrace-oneagent-operator/templates/Kubernetes/podsecuritypolicy-operator.yaml#L20 you use the chart release name:

`name: {{ .Release.Name }}`

However, in https://github.com/Dynatrace/helm-charts/blob/d5e07b3a9ce4f06deacf87643a63d4f26f86e538/dynatrace-oneagent-operator/templates/Kubernetes/role-operator.yaml#L118 you use the hard coded name to reference to the psp:

`dynatrace-oneagent-operator`

Shouldn't there also be used the .Release.Name variable? Otherwise everyone needs to use the release name "dynatrace-oneagent-operator"

**Comment by lrgar** [comment]
Hello there.

Yes, you're right. We'll fix it for our next release.

Regards,
Luis

**Comment by DTMad** [comment]
Hey!

This has been fixed here:
https://github.com/Dynatrace/helm-charts/pull/26

Once the PR is merged and the new version is released you can use it.

Regards,
Marco
