### ISSUE TITLE
Missing caBundle in MutatingWebhookConfiguration when deploying Helm chart to OpenShift 3.11

### ISSUE THREAD

**Issue by ToniCipriani** [Dynatrace/helm-charts#35]
Error when attempting to perform a Helm chart deployment to an OpenShift 3.11 cluster.

Cluster is air-gapped and the URL used is a DynaTrace ActiveGate. ActiveGate is confirmed working and shows up in cluster deployment status.

Chart version `0.8.0`.

```
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(MutatingWebhookConfiguration.webhooks[0]): unknown field "admissionReviewVersions" in io.k8s.api.admissionregistration.v1beta1.Webhook, ValidationError(MutatingWebhookConfiguration.webhooks[0].clientConfig): missing required field "caBundle" in io.k8s.api.admissionregistration.v1beta1.WebhookClientConfig, ValidationError(MutatingWebhookConfiguration.webhooks[0].rules[0]): unknown field "scope" in io.k8s.api.admissionregistration.v1beta1.RuleWithOperations]
```

**Comment by lrgar** [comment]
Hello there!

Thank you for your message. Could you please create a Support Ticket on Dynatrace so that we can take a proper look. We haven't seen this in our OCP 3.11 environments, so there could be some differences between our environments and yours.

Thanks and best regards,
Luis
