### ISSUE TITLE
helm-charts release not updated to v0.9.0

### ISSUE THREAD

**Issue by benj5656** [Dynatrace/helm-charts#45]
oneagent-operator is now at v0.9.0:
https://github.com/Dynatrace/dynatrace-oneagent-operator/releases/tag/v0.9.0

Can the helm-charts also be updated to this release?

**Comment by DTMad** [comment]
Hey!
We will do the release for the helm chart as soon as possible.

**Comment by benj5656** [comment]
Great, thanks :)
