### ISSUE TITLE
Error when deploying dynatrace-oneagent-operator chart version 0.9.2

### ISSUE THREAD

**Issue by ZF-fredericvanlinthoudt** [Dynatrace/helm-charts#53]
Error when deploying dynatrace-oneagent-operator chart version 0.9.2 when setting nodeSelector and tolerations:
` YAML parse error on dynatrace-oneagent-operator/templates/Common/deployment-webhook.yaml: error converting YAML to JSON: yaml: line 130: mapping values are not allowed in this context`

@DTMad 
Probably due a copy/paste error over here:
https://github.com/Dynatrace/helm-charts/blob/master/dynatrace-oneagent-operator/templates/Common/deployment-webhook.yaml#L133
```
{{- end -}}
```
I think it should be:
```
{{- end }}
```

**Comment by DTMad** [comment]
@ZF-fredericvanlinthoudt Thank you very much for your notice!
We already fixed it and updated the release.

Please let us know if you experience any further problems.

Thanks,
Marco
