### ISSUE TITLE
Questions.yaml does not allow resource quota's to be set

### ISSUE THREAD

**Issue by MG2R** [Dynatrace/helm-charts#57]
The `resources` key for oneagent in questions.yaml is of string type. However, the resources key in the templates needs to be an object in order for the `toYaml` to work [here](https://github.com/Dynatrace/helm-charts/blob/master/dynatrace-oneagent-operator/templates/Common/customresource-oneagent.yaml#L61). I can correctly define the resources when going through CLI Helm and a values file. I can't correctly define them when going through a system that adheres to questions.yaml (like Rancher).

**Comment by DTMad** [comment]
Hey, @MG2R,
yes, we are aware of that problem but this basically is because of a limitation of Rancher.
However there's the possibility in rancher to switch to the yaml instead of the form and there you can fill them properly.
We tried to make our customers aware by putting 'Please edit as Yaml for the best experience. The expected format is YAML and not a string'

Hopefully Rancher will provide a way to properly put fields like them.
Hope that helps,
Marco

**Comment by MG2R** [comment]
No, that's not it. If I edit the YAML, and enter

```
oneagent:
  resources:
    limits:
      memory: 1Gi
    requests:
      memory: 1Gi
```

The result is that this value is not passed on to the helm installation at all. A subsequent edit will just show me the default `resources: ''` again.

If I enter the value as a String, like this:

```
oneagent:
  resources: |
    limits:
      memory: 1Gi
    requests:
      memory: 1Gi
```

Then the value DOES get passed on to the helm installation, HOWEVER it won't actually successfully apply. Helm errors out with saying `spec.resources` should be of type object.

If I install dynatrace-oneagent-operator through rancher without specifying the resources, and THEN use the CLI to issue a helm upgrade which specifies the resources in the first way shown above, everything works as expect, indicating the issue is specifically with questions.yaml, and not with values.yaml.

The issue lies in the fact that the `toYaml` [here](https://github.com/Dynatrace/helm-charts/blob/master/dynatrace-oneagent-operator/templates/Common/customresource-oneagent.yaml#L61) only works if I enter an object (i.e. the first way above), but the questions.yaml specifically restricts input via rancher to be a string, right [here](https://github.com/Dynatrace/helm-charts/blob/master/dynatrace-oneagent-operator/questions.yml#L168).

There's two possible solutions:

1. Change the line in `customresource-oneagent.yaml` to simply use a string, instead of `toYaml`-ing an object, then accept a multiline string in questions.yaml, as you already do for [the CA definition](https://github.com/Dynatrace/helm-charts/blob/master/dynatrace-oneagent-operator/questions.yml#L124). This would allow us to use the second way of passing on the resource quota mentioned above.
2. Change the questions.yaml to not specify the resources anymore. That would stop Rancher from parsing that bit and throwing out the "invalid" data.

I strongly prefer solution 1.

**Comment by DTMad** [comment]
You're right, thanks!

We will go for the first solution and implement it.
It will be released with the next version.

**Comment by DTMad** [comment]
Will be available with Helm chart v0.9.2 on Rancher and with the next release for the "normal" helm chart

**Comment by MG2R** [comment]
@DTMad I'm not sure about the release process for this. Could you maybe give an indication as to when the Rancher charts are released? Or is this something not under your control?

Thanks!

**Comment by DTMad** [comment]
He @MG2R,

to publish our new versions on Rancher we need to create a PR on their repository:
https://github.com/rancher/helm3-charts/pulls

0.9.2 got merged already and should be available:
https://github.com/rancher/helm3-charts/pull/46

Thanks!

**Comment by MG2R** [comment]
Interesting. It seems that out of the box, this is the repo Ranchers gets dynatrace charts from: https://github.com/rancher/partner-charts

I decided to roll out the charts using the official dynatrace repo. Everything works now.

Thank you again for your help in this! Greatly appreciated.

**Comment by DTMad** [comment]
Glad it works for you now!
No problem ;)
