### ISSUE TITLE
Add the ability to specify podAnnotations

### ISSUE THREAD

**Issue by kav** [Dynatrace/helm-charts#77]
Our particular use case requires speccing `cluster-autoscaler.kubernetes.io/safe-to-evict: "true"` on the webhook pod to allow the cluster autoscaler to reschedule it and decomission the node but I expect others will have additional needs based on their cluster configuration

**Comment by meik99** [comment]
This Dynatrace/helm-charts repository has been deprecated. If you have the same issues with the latest charts, please open this issue in the [Dynatrace/dynatrace-operator](https://github.com/Dynatrace/dynatrace-operator) repository
