### ISSUE TITLE
Allow easy use of internal regsitries

### ISSUE THREAD

**Issue by MG2R** [Dynatrace/helm-charts#80]
Right now, if you don't manually specify the image to use, by default the image name is hardcoded to come from "docker.io", for example [here](https://github.com/Dynatrace/helm-charts/blob/334bcf1056f08e91137f5efefa76033ce71ced29/dynatrace-oneagent-operator/templates/_helpers.tpl#L82). Is there a specific reason for doing that? As far as I know specifying `dynatrace/<image>` should be functionally the same as `docker.io/dynatrace/<image>`.

The issue I'm having right now is that I'm trying to roll out dynatrace oneagents in an air-gapped kubernetes cluster. We have an internal docker.io proxy which is the default in the kubernetes cluster. Any image not specifying the registry will get pulled from our internal proxy. This means we don't hit docker.io directly or as frequently, thus avoiding lots of internet traffic and rate limiting.

Because the chart hard-codes `docker.io` as the registry, I need to overwrite the images and keep track of versioning and naming for those, manually. It's doable, but it strikes me as extra work that can be easily avoided. I don't really want to override the image names, but that seems to be the only option for overriding the registry.

Would you consider not hardcoding the registry, or moving the registry to a value? Or is there something about this I'm misunderstanding? It's quite possible I'm not fully understanding the purpose of prepending `docker.io`.

**Comment by lrgar** [comment]
Hi. The reason is that our official image is in `docker.io`. Customers can have their own default registries and not include docker.io for example.

That being said, isn't it OK for you to set `--set oneagent.image=dynatrace/oneagent:latest`? It would end up being the same as you are requesting.

Best regards,
Luis

**Comment by MG2R** [comment]
The only issue with that, I think, is that it would change the Helm chart functionality. Right now, installing version 0.9.5 of the Helm chart, installs version 0.9.5 of the oneagent. If I just specify `latest` in the image, it’s possible that I’m installing a version of the oneagent which is newer than and, worse, incompatible with the resources in the specific chart that is used to install it. 

Would you consider making the inclusion of `docker.io` as the registry a variable? That way, you can keep the chart identical for customers not running in an air-gapped environment and using the defaults, but it would allow customers like us to only override the registry only and not have to keep track of the chart/application versions.
