### ISSUE TITLE
Allow setting resources for webhook deployment via values.yaml file

### ISSUE THREAD

**Issue by F28956** [Dynatrace/helm-charts#86]
On one of our clusters dynatrace webhook gets  CPU throttled, while remediation is pretty easy by fine tuning resources for dynatrace webhook, it's currently not possible to do so via helm charts, as resource values are hardcoded: https://github.com/Dynatrace/helm-charts/blob/master/dynatrace-oneagent-operator/templates/Common/deployment-webhook.yaml#L97-L103

It would be very useful to be able to set resources via values.yaml file

**Comment by F28956** [comment]
Pull request: https://github.com/Dynatrace/helm-charts/pull/87

**Comment by luhi-DT** [comment]
Hi, this was done with https://github.com/Dynatrace/dynatrace-operator/pull/446 , thanks for your input
