### ISSUE TITLE
dynatrace-operator - allow to create Dynakube without specifying tokens in values

### ISSUE THREAD

**Issue by Anna-Katona** [Dynatrace/helm-charts#89]
Hello!

We would like to create Dynakube without specifying apiToken and passToken in values.yaml and create the secret that contains these vars manually (the same way it is done in dynatrace-openagent-operator). Can this dependency will be removed? https://github.com/Dynatrace/helm-charts/blob/master/dynatrace-operator/templates/Common/customresource-dynakube.yaml#L16
{{- if and (.Values.apiUrl) (.Values.apiToken) (.Values.paasToken) }} -> {{- if .Values.apiUrl }}

Thanks!

**Comment by kav** [comment]
We would also greatly appreciate support for this, ideal allowing the ability to provide a secret to read this from though I don't know how that'd play with the CRD

**Comment by DTMad** [comment]
You can disable the automatic creation of secrets by setting this to false:
https://github.com/Dynatrace/helm-charts/blob/master/dynatrace-operator/values.yaml#L28

Does this solve your use case?
