### ISSUE TITLE
oneagent-operator helm chart doesn't support defining an image pull secret

### ISSUE THREAD

**Issue by rahul-mereddy** [Dynatrace/helm-charts#97]
I couldn't find the image pull secret for dynatrace oneagent-operator in the helm chart repo.

Due to the recent dockerhub rate limit pull issues causing imagepull errors on our kubernetes clusters and moved oneagent operator image to private GAR repo and to pull the image from private repository it need a imagepull secret but unfortunately oneagent-operator helm chart doesn't support defining an image pull secret.

**Documentation for installing dynatrace on kubernetes clyster:** https://www.dynatrace.com/support/help/technology-support/cloud-platforms/kubernetes/other-deployments-and-configurations/deploy-oneagent-k8/?deploy-with-kubectl%3C-%3Edeploy-with-helm=deploy-with-helm#install-oneagent-operator
 
Dynatrace helm chart repo: https://github.com/Dynatrace/helm-charts.

![image](https://user-images.githubusercontent.com/30416525/118512623-969dca00-b6f8-11eb-9fcc-5ea679eff5f0.png)

oneagent image pull secret is defined: https://github.com/Dynatrace/helm-charts/blob/0c115ffef79e4e8a8b97a96142c94c8c8b34d406/dynatrace-oneagent-operator/values.yaml#L62

oneagent-operator is missing the image pull secret define: https://github.com/Dynatrace/helm-charts/blob/0c115ffef79e4e8a8b97a96142c94c8c8b34d406/dynatrace-oneagent-operator/values.yaml#L21

**Comment by DTMad** [comment]
Fixed by https://github.com/Dynatrace/helm-charts/pull/98 and released with the latest release:
https://github.com/Dynatrace/helm-charts/releases/tag/dynatrace-operator-v0.2.2
