### ISSUE TITLE
Permissions and mount creation issue

### ISSUE THREAD

**Issue by devopsangel** [Dynatrace/helm-charts#99]
Hi team, 

I am on `GKE - 1.19.9-gke.1900` and facing following issue:

![image](https://user-images.githubusercontent.com/54945914/120714677-81af8d80-c491-11eb-957d-93b11cebf893.png)

Any thoughts how to resolve it?

**Comment by sbillon** [comment]
Got same issue on GKE 1.18

08:17:04 Started agent deployment as a container, PID 2391527.                                                                                                                                                                                                               
08:17:04 Downloading agent to /tmp/Dynatrace-OneAgent-Linux.sh via https://XXXXX.live.dynatrace.com/api/v1/deployment/installer/agent/unix/default/latest?Api-Token=***&arch=x86&flavor=default                                                                           
08:17:07 Download complete                                                                                                                                                                                                                                                   
08:17:07 Warning: Cannot change permissions of /mnt/host_root/opt directory to u+rwx,g+rx,o+rx.                                                                                                                                                                              
08:17:07 Warning: Cannot create /mnt/host_root/opt/dynatrace/oneagent directory.                                                                                                                                                                                             
mv: cannot move '/tmp/Dynatrace-OneAgent-Linux.sh' to '/mnt/host_root/opt/dynatrace/oneagent/Dynatrace-OneAgent-Linux.sh': No such file or directory

**Comment by devopsangel** [comment]
@sbillon pass this env.

![image](https://user-images.githubusercontent.com/54945914/122231518-7d6b7300-ce88-11eb-87f8-8a9f4a9c0e37.png)
